# Generated by Django 5.2.17 on 2026-08-17 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manutencao', 'Manutenção Geral'), ('troca_pneus', 'Troca de Pneus'), ('troca_oleo', 'Troca de Óleo'), ('revisao', 'Revisão'), ('freios', 'Freios'), ('outro', 'Outro')], max_length=20, verbose_name='Tipo de Serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data do Serviço')),
                ('quilometragem', models.IntegerField(blank=True, null=True, verbose_name='Quilometragem')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Custo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='veiculos.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
                'ordering': ['-data'],
            },
        ),
    ]
